run:
  timeout: 5m
  tests: true
  issues-exit-code: 2

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false

linters:
  disable-all: true
  enable:
    # correctness & robustness
    - errcheck
    - errorlint
    - govet
    - staticcheck
    - unused
    - ineffassign
    - bodyclose

    # size
    - funlen
    - lll

    # safety & hygiene
    - gosec
    - nolintlint

    # architecture / discipline
    - depguard
    - gochecknoglobals
    - gochecknoinits
    - forbidigo

linters-settings:
  funlen:
    lines: 250
    statements: 150
    ignore-comments: true

  lll:
    line-length: 200
    tab-width: 1

  nolintlint:
    allow-unused: false
    require-explanation: true
    allow-no-explanation: []

  errcheck:
    check-type-assertions: true
    check-blank: true
    disable-default-exclusions: true

  gosec:
    includes: []

  forbidigo:
    forbid:
      - p: ^print(ln)?$
      - p: ^fmt\.Print.*$
        msg: "Do not commit print statements (use structured logging)."
      - p: ^log\..*$
        msg: "Do not use stdlib log; use tflog from terraform-plugin-log."
    exclude-godoc-examples: true

  depguard:
    rules:
      main:
        list-mode: lax
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "Use standard library errors + wrapping."
          - pkg: "io/ioutil$"
            desc: "io/ioutil is deprecated; use os/io."
