version: "2"

run:
  timeout: 5m
  tests: true
  issues-exit-code: 2

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false

linters:
  default: none
  enable:
    # correctness & robustness
    - errcheck
    - errorlint
    - govet
    - staticcheck
    - unused
    - ineffassign
    - bodyclose

    # size
    - funlen
    - lll

    # safety & hygiene
    - gosec
    - nolintlint

    # architecture / discipline
    - depguard
    - gochecknoglobals
    - gochecknoinits
    - forbidigo
  settings:
    funlen:
      lines: 1000
      statements: 800
      ignore-comments: true

    lll:
      line-length: 320
      tab-width: 1

    nolintlint:
      allow-unused: false
      require-explanation: true
      allow-no-explanation: []

    errcheck:
      check-type-assertions: true
      check-blank: true
      disable-default-exclusions: true

    gosec:
      includes: []

    forbidigo:
      forbid:
        - pattern: ^print(ln)?$
        - pattern: ^fmt\.Print.*$
          msg: "Do not commit print statements (use structured logging)."
        - pattern: ^log\..*$
          msg: "Do not use stdlib log; use tflog from terraform-plugin-log."
      exclude-godoc-examples: true

    depguard:
      rules:
        main:
          list-mode: lax
          files:
            - $all
          deny:
            - pkg: "github.com/pkg/errors"
              desc: "Use standard library errors + wrapping."
            - pkg: "io/ioutil$"
              desc: "io/ioutil is deprecated; use os/io."
